### PR TITLE
fix: check null ref before removeEventListener

### LINKED ISSUE #178: 组件卸载时概率性报错
https://github.com/ant-design/ant-design/issues/35221

### PR DESCRIPTION
**Pull request by DeepAnchor**
Fixes error "Cannot read property removeEventListener of null" 

Related issues: 
close https://github.com/react-component/virtual-list/pull/163
close https://github.com/ant-design/ant-design/issues/34816
close https://github.com/ant-design/ant-design/issues/35221
close #178

### CODE REVIEW

**Comment by nuintun** [comment]
https://github.com/react-component/virtual-list/issues/178

File: src/ScrollBar.tsx [hunk 1]
```diff
@@ -89,10 +89,15 @@ export default class ScrollBar extends React.Component<ScrollBarProps, ScrollBar
     window.removeEventListener('mousemove', this.onMouseMove);
     window.removeEventListener('mouseup', this.onMouseUp);
 
-    this.scrollbarRef.current.removeEventListener('touchstart', this.onScrollbarTouchStart);
-    this.thumbRef.current.removeEventListener('touchstart', this.onMouseDown);
-    this.thumbRef.current.removeEventListener('touchmove', this.onMouseMove);
-    this.thumbRef.current.removeEventListener('touchend', this.onMouseUp);
+    if (this.scrollbarRef.current) {
+      this.scrollbarRef.current.removeEventListener('touchstart', this.onScrollbarTouchStart);
+    }
```
Comment (afc163) [inline src/ScrollBar.tsx:94]:
```suggestion
      this.scrollbarRef.current?.removeEventListener('touchstart', this.onScrollbarTouchStart);
```

File: src/ScrollBar.tsx [hunk 2]
```diff
@@ -89,10 +89,13 @@ export default class ScrollBar extends React.Component<ScrollBarProps, ScrollBar
     window.removeEventListener('mousemove', this.onMouseMove);
     window.removeEventListener('mouseup', this.onMouseUp);
 
-    this.scrollbarRef.current.removeEventListener('touchstart', this.onScrollbarTouchStart);
-    this.thumbRef.current.removeEventListener('touchstart', this.onMouseDown);
-    this.thumbRef.current.removeEventListener('touchmove', this.onMouseMove);
-    this.thumbRef.current.removeEventListener('touchend', this.onMouseUp);
+      this.scrollbarRef.current?.removeEventListener('touchstart', this.onScrollbarTouchStart);
```
Comment (afc163) [inline src/ScrollBar.tsx:92]:
```suggestion
    this.scrollbarRef.current?.removeEventListener('touchstart', this.onScrollbarTouchStart);
```
